sonar.projectKey=SEU_USUARIO_SEU_PROJETO
sonar.organization=SEU_USUARIO_SONARCLOUD

sonar.projectName=Static Site - IVORY DevOps Test
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.github/**,**/*.md

sonar.sourceEncoding=UTF-8
