sonar.projectKey=fantineF_ivory-devops-test
sonar.organization=fantinef

sonar.projectName=Static Site - IVORY DevOps Test
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.github/**,**/*.md

sonar.sourceEncoding=UTF-8
